import {actionNames} from 'constants/index';
const actions ={};

actions.SOLICITUD_EMPADRONAMIENTO_SET_LUGAR_RESIDENCIA =(state)=>{
    return { type:actionNames.SOLICITUD_EMPADRONAMIENTO_SET_LUGAR_RESIDENCIA, state};
}
actions.SOLICITUD_EMPADRONAMIENTO_SET_STEP =(state)=>{
    return { type:actionNames.SOLICITUD_EMPADRONAMIENTO_SET_STEP, state};
}

actions.SOLICITUD_EMPADRONAMIENTO_SET_SOLICITUDES =(state)=>{
    return { type:actionNames.SOLICITUD_EMPADRONAMIENTO_SET_SOLICITUDES, state};
}
actions.SOLICITUD_EMPADRONAMIENTO_SET_DATOS_CIUDADANO_TABLE =(state)=>{
    return { type:actionNames.SOLICITUD_EMPADRONAMIENTO_SET_DATOS_CIUDADANO_TABLE, state};
}
actions.SOLICITUD_EMPADRONAMIENTO_SET_DATOS_RESIDENCIA =(state)=>{
    return { type:actionNames.SOLICITUD_EMPADRONAMIENTO_SET_DATOS_RESIDENCIA, state};
}
actions.SOLICITUD_EMPADRONAMIENTO_SET_ARRAY_LISTADO =(state)=>{
    return { type:actionNames.SOLICITUD_EMPADRONAMIENTO_SET_ARRAY_LISTADO, state};
}
actions.SOLICITUD_EMPADRONAMIENTO_SET_DATOS_SOLICITUD_RENAP =(state)=>{
    return { type:actionNames.SOLICITUD_EMPADRONAMIENTO_SET_DATOS_SOLICITUD_RENAP, state};
}
actions.SOLICITUD_EMPADRONAMIENTO_SET_DATOS_IDENTIDAD =(state)=>{
    return { type:actionNames.SOLICITUD_EMPADRONAMIENTO_SET_DATOS_IDENTIDAD, state};
}
actions.SOLICITUD_EMPADRONAMIENTO_SET_ES_RECHAZADO_O_EMPADRONADO =(state)=>{
    return { type:actionNames.SOLICITUD_EMPADRONAMIENTO_SET_ES_RECHAZADO_O_EMPADRONADO, state};
}
actions.SOLICITUD_EMPADRONAMIENTO_SET_RECHAZAR_SOLICITUD =(state)=>{
    return { type:actionNames.SOLICITUD_EMPADRONAMIENTO_SET_RECHAZAR_SOLICITUD, state};
}
actions.SOLICITUD_EMPADRONAMIENTO_SET_CUI_DPI =(state)=>{
    return { type:actionNames.SOLICITUD_EMPADRONAMIENTO_SET_CUI_DPI, state};
}
actions.SOLICITUD_EMPADRONAMIENTO_SET_ESTA_EMPADRONADO =(state)=>{
    return { type:actionNames.SOLICITUD_EMPADRONAMIENTO_SET_ESTA_EMPADRONADO, state};
}
actions.SOLICITUD_EMPADRONAMIENTO_SET_ESTA_FALLECIDO =(state)=>{
    return { type:actionNames.SOLICITUD_EMPADRONAMIENTO_SET_ESTA_FALLECIDO, state};
}
actions.SOLICITUD_EMPADRONAMIENTO_SET_EVENTO_RENAP =(state)=>{
    return { type:actionNames.SOLICITUD_EMPADRONAMIENTO_SET_EVENTO_RENAP, state};
}
actions.SOLICITUD_EMPADRONAMIENTO_SET_DATOS_EMPADRONADOR =(state)=>{
    return { type:actionNames.SOLICITUD_EMPADRONAMIENTO_SET_DATOS_EMPADRONADOR, state};
}
actions.SOLICITUD_EMPADRONAMIENTO_SET_DONT_ALLOW_CHANGE =(state)=>{
    return { type:actionNames.SOLICITUD_EMPADRONAMIENTO_SET_DONT_ALLOW_CHANGE, state};
}

