const loser= [  {"url":"AHHHHHHHHHHHHHHHHHHHHHH.mp4"},
                {"url":"algo anda mal.mp4"},
                {"url":"aqui les pregunto que hubieran hecho ustedes.mp4"},
                {"url":"Bob Espona llorando(despedido)- Plantillas para memes.mp4"},
                {"url":"dejame tocar esta cancion saddest.mp4"},
                {"url":"El hombre araña- He vuelto, he vuelto a caer- Plantillas para memes- momos.mp4"},
                {"url":"En ese momento cell sintio el verdadero terror- Dragon ball.mp4"},
            ];
const start=[   {"url":"ahora si viene lo shido.mp4"},
                {"url":"asi que veremos que sucede estoy algo nervioso.mp4"},
                {"url":"Asustado Potter- Plantillas para memes- momos.mp4"},
                {"url":"esta cosa es real hijo.mp4"},
                {"url":"estas retandome.mp4"},
                {"url":"hola a todos que tal como estais.mp4"},
                {"url":"quieres que me ponga rudo eh-1.mp4"},
                {"url":"y ahora dorotil tiene una pregunta.mp4"},
            ]
const winner=[  {"url":"A eso se le llama estrategia- Plantilla para memes.mp4"},
                {"url":"cielos que macizo.mp4"},
                {"url":"con honor hasta al final.mp4"},
                {"url":"el macho.mp4"},
                {"url":"el poder esta en el traje.mp4"},
                {"url":"es bellisimo.mp4"},
                {"url":"ese soy yo bob esponja pantalones valientes.mp4"},
                {"url":"eso si es de gangsters.mp4"},
                {"url":"este muchacho me llena de orgullo.mp4"},
                {"url":"hiciste lo correcto bob.mp4"},
                {"url":"Inteligente noooo- Plantillas para memes- momos.mp4"},
                {"url":"lo logro señor.mp4"},
                {"url":"Maravillosa jugada video- Plantilla para memes.mp4"},
                {"url":"mi mente es superior ala de los demas.mp4"},
                {"url":"Miren el tamaño de esos huevos- Plantilla para memes.mp4"},
                {"url":"no puedo argumentar nada ante esa logica.mp4"},
                {"url":"que haria esta ciudad sin ti bob esponja.mp4"},
                {"url":"que jugada fue esa.mp4"},
                {"url":"si se pudo si se pudoo.mp4"},
                {"url":"siempre he admirado a los hombres exitosos.mp4"},
                {"url":"sustos que dan gusto.mp4"},
                {"url":"tienes mi respeto stark.mp4"},
                {"url":"vieron eso, eso es ser barbaro.mp4"},
                {"url":"wowow mas despacio velocista.mp4"},
                {"url":"y eso que decian que nunca iba a servir para nada.mp4"},
                {"url":"yo soy el guerrero dragon.mp4"},
                {"url":"yo soy el sujetoo.mp4"}]

export const media={"loser":loser,"start":start,"winner":winner};
